apiVersion: v1
kind: Service
metadata:
  name: mysql-svc-g15
  labels:
    app: mysql-g15
spec:
  type: ClusterIP
  selector:
    app: mysql-g15
  ports:
    - name: mysql-g15
      port: 3306
      targetPort: 3306
 