apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-g15
  labels:
    app: mysql-g15
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: mysql-g15
  template:
    metadata:
      labels:
        app: mysql-g15
    spec:
      containers:
      - image: 835867664638.dkr.ecr.us-east-1.amazonaws.com/mysql:v1.0
        name: mysql-g15
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: clo835
        ports:
        - containerPort: 3306
          protocol: TCP
        volumeMounts:
        - name: mysql-database
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-database
        persistentVolumeClaim: 
          claimName: mysql-pvc15
