apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc15
  labels:
    name: mysql-pvc15
  namespace: final
spec:
  storageClassName: gp2
  resources:
    requests:
      storage: 2Gi
  accessModes:
    - ReadWriteOnce
